name: hotspot_hosts_flutter_assignment
description: Hotspot Hosts Flutter Assignment - Clean Architecture + BLoC scaffold
publish_to: "none"
version: 0.0.1
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  equatable: ^2.0.5
  get_it: ^9.0.5
  dio: ^5.0.2
  logger: ^1.1.0
  go_router: ^7.0.0
  permission_handler: ^10.4.1
  record: ^6.1.2
  camera: ^0.11.0+2
  audioplayers: ^6.1.0
  video_player: ^2.9.1
  cached_network_image: ^3.2.3
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
